### ISSUE TITLE
indexation du contenu des bases colectica

### ISSUE THREAD

**Issue by dzkwsk** [InseeFr/DDI-Access-Services#94]
relancer l'indexation du contenu des bases Colectica. Du contenu existant n'est pas trouvable. 

normalement elle devrait se lancer toutes les 5 minutes, quel moyen pour vérifier que l'indexation est toujours 'UP' ?

**Comment by FBibonne** [comment]
@dzkwsk  de quelle base / quelle plateforme parles-tu ?

**Comment by CatherineGoillot** [comment]
Voir pour clôturer cette carte.

**Comment by dzkwsk** [comment]
C'était sur la dev3 Colectica. Jérôme m'a dit que l'indexation avait
tourné. On peut clôturer la carte

Le lun. 9 sept. 2024, 09:28, Fabrice Bibonne ***@***.***> a
écrit :
